package cs4620.framework;

import javax.media.opengl.GL2;

public class GLError {
	public static boolean printErrors = true;
	
	public static void get(GL2 gl, String description) {
		// grab and report any errors generated by OpenGL since the last time they were checked
		// based on http://forum.jogamp.org/glBufferData-and-glBufferSubData-seems-not-to-work-td3267295.html
		int error;
		boolean foundError = false;
		if(!printErrors)
			return; // don't keep spamming the user after first display() invocation
		
		while((error = gl.glGetError()) != GL2.GL_NO_ERROR)
		{
			if(!foundError)
			{
				System.out.print("ERROR - " + description + " - ");
				foundError = true;
			}
			System.out.print(error);
			System.out.print(" ");
		}
		if(foundError)
			System.out.println("");
	}
}
